import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { openStore } from '../lib/store.mjs';
import { defaults, validateConfig } from '../lib/config.mjs';
import { createWorker, estimate } from '../lib/worker.mjs';
import { validateProject } from '../core.mjs';
function fixture(t){const dir=mkdtempSync(path.join(tmpdir(),'studio-test-'));const store=openStore(dir);t.after(()=>{store.db.close();rmSync(dir,{recursive:true,force:true});});return store;}
test('budget reservations atomic, duplicate jobs rejected, secrets encrypted',t=>{const s=fixture(t);const p=s.save('a'.repeat(24),validateProject({title:'A'}));s.setSecret('gemini','private-test-value');assert.equal(s.secret('gemini'),'private-test-value');assert.ok(!s.db.prepare('SELECT value FROM settings').get().value.includes('private-test-value'));const j=s.enqueue(p,'story',{},1,{perVideo:2,daily:2,monthly:3});assert.throws(()=>s.enqueue(p,'story',{},1,defaults),/zaten/);s.updateJob(j,'done','ok');assert.throws(()=>s.enqueue(p,'story',{},2,{perVideo:3,daily:2,monthly:3}),/bütçe/);assert.equal(s.totals().day,1);});
test('paid step with uncertain network result is not repeated on resume',async t=>{const s=fixture(t);s.setSecret('gemini','test');s.setSetting('config',{...defaults,paid:true,pricesConfirmed:true,minFreeGB:0.001});const p=s.save('b'.repeat(24),validateProject({title:'A'}));const j=s.enqueue(p,'story',{},0.1,defaults);let calls=0;const w=createWorker(s,{}, {providerFactory:()=>({text:async()=>{calls++;throw Error('network lost');}})});await w.tick();assert.equal(s.job(j.id).status,'failed');assert.equal(calls,1);const retry=s.job(j.id);s.updateJob(retry,'queued','retry');await w.tick();assert.equal(calls,1);assert.match(s.job(j.id).message,/belirsiz/);});
test('successful story persists short-length scenes and releases project lock',async t=>{const s=fixture(t);s.setSecret('gemini','test');s.setSetting('config',{...defaults,paid:true,pricesConfirmed:true,minFreeGB:0.001});const p=s.save('c'.repeat(24),validateProject({title:'A',idea:'A fox walks in the forest.',length:'short'}));const j=s.enqueue(p,'story',{},0.1,defaults);const w=createWorker(s,{}, {providerFactory:()=>({text:async()=>({scenes:Array.from({length:3},()=>({visual:'fox',motion:'walk',narration:'Hi'}))})})});await w.tick();assert.equal(s.job(j.id).status,'done');assert.equal(s.project(p.id).scenes.length,3);assert.equal(s.job(j.id).context.projectVersion,s.project(p.id).updated);});
test('configuration rejects unsafe origins and invalid budgets',()=>{assert.throws(()=>validateConfig({...defaults,publicUrl:'http://evil.example'}));assert.throws(()=>validateConfig({...defaults,daily:-1}));assert.throws(()=>validateConfig({...defaults,minFreeGB:0}));assert.throws(()=>validateConfig({...defaults,videoModel:'../../foo'}));assert.equal(validateConfig({...defaults,publicUrl:'https://studio.example.com'}).publicUrl,'https://studio.example.com');assert.equal(validateConfig({...defaults,textModel:'gemini-2.5-pro',minFreeGB:3}).minFreeGB,3);assert.equal(validateConfig({...defaults,provider:'web'}).provider,'web');assert.equal(validateConfig({...defaults,provider:'bogus'}).provider,'api');});
test('pipeline estimate charges only for missing scenes',()=>{assert.equal(estimate('pipeline',{scenes:[{image:{},clip:{}}]},defaults),0);assert.equal(estimate('pipeline',{scenes:[{image:{}},{image:{},clip:{}}]},defaults),defaults.textReserve+8*defaults.videoSecondPrice);assert.equal(estimate('pipeline',{scenes:[],length:'short'},defaults),defaults.textReserve*2+3*(8*defaults.videoSecondPrice));});
test('web provider gate refuses to run without a session file',async t=>{const s=fixture(t);const cfg={...defaults,provider:'web',minFreeGB:0.001};s.setSetting('config',cfg);
  const p=s.save('f'.repeat(24),validateProject({title:'W',idea:'Walk.',scenes:[{visual:'a',motion:'b'}]}));
  const j=s.enqueue(s.project(p.id),'image',{},0,cfg);
  const w=createWorker(s,{}, {providerFactory:()=>({image:async()=>({mimeType:'image/png',data:'AA=='})}),render:async()=>({}),available:async()=>true,freeSpace:async()=>99});
  await w.tick();assert.equal(s.job(j.id).status,'failed');assert.match(s.job(j.id).message,/oturum/i);});
test('pipeline with fully uploaded scenes needs no provider and renders only',async t=>{const s=fixture(t);s.setSetting('config',{...defaults,autoSharePool:false,minFreeGB:0.001});const p=s.save('e'.repeat(24),validateProject({title:'Manuel',idea:'A short walk.',scenes:[{visual:'a',motion:'b'}]}));p.scenes[0].image={file:'x.png',mimeType:'image/png'};p.scenes[0].clip={file:'x.mp4'};s.save(p.id,p);const j=s.enqueue(s.project(p.id),'pipeline',{autoUpload:false},0,{...defaults,autoSharePool:false});let providerCalled=false;const rendered={file:'r/output.mp4',bytes:3};const w=createWorker(s,{}, {providerFactory:()=>({text:async()=>{providerCalled=true;},image:async()=>{providerCalled=true;},startVideo:async()=>{providerCalled=true;}}),render:async()=>rendered,available:async()=>true,freeSpace:async()=>99});const {mkdirSync:mk,writeFileSync:wf}=await import('node:fs');const dir=path.join(s.directory,'media',p.id,'r');mk(dir,{recursive:true});wf(path.join(dir,'output.mp4'),'abc');await w.tick();assert.equal(providerCalled,false);assert.equal(s.job(j.id).status,'done',s.job(j.id).message);assert.equal(s.project(p.id).output.file,'r/output.mp4');assert.equal(s.project(p.id).pool.status,'ready');});

